# Generated by Django 5.2.1 on 2025-09-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_loginlog_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="是否软删除",
                        default=False,
                        verbose_name="是否软删除",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="参数名称",
                        default="",
                        max_length=100,
                        verbose_name="参数名称",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_comment="参数键名",
                        default="",
                        max_length=100,
                        verbose_name="参数键名",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        db_comment="参数键值",
                        default="",
                        max_length=500,
                        verbose_name="参数键值",
                    ),
                ),
                (
                    "config_type",
                    models.BooleanField(
                        db_comment="系统内置（1是 0否）",
                        default=False,
                        verbose_name="系统内置",
                    ),
                ),
            ],
            options={
                "verbose_name": "参数配置",
                "verbose_name_plural": "参数配置",
                "ordering": ["-id"],
            },
        ),
    ]
