# Generated by Django 5.2.1 on 2025-10-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0004_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        help_text="备注",
                        max_length=256,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        db_comment="创建人",
                        help_text="创建人",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        blank=True,
                        db_comment="修改人",
                        help_text="修改人",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="修改时间",
                        help_text="修改时间",
                        null=True,
                        verbose_name="修改时间",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_comment="是否软删除",
                        default=False,
                        verbose_name="是否软删除",
                    ),
                ),
                ("prov_id", models.IntegerField(verbose_name="省id")),
                ("prov_name", models.CharField(max_length=255, verbose_name="省")),
                ("city_id", models.IntegerField(verbose_name="市id")),
                ("city_name", models.CharField(max_length=255, verbose_name="市")),
                ("area_id", models.IntegerField(verbose_name="区id")),
                ("area_name", models.CharField(max_length=255, verbose_name="区")),
            ],
            options={
                "verbose_name": "省市区",
                "verbose_name_plural": "省市区",
                "db_table": "system_city_area",
            },
        ),
    ]
